# Generated by Django 3.2.5 on 2021-07-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.CharField(default='', max_length=200),
        ),
    ]
