# Generated by Django 3.2.5 on 2021-07-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdie', '0002_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='', max_length=200),
        ),
    ]
